# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import sc2anonserverpy.grpc_functions.anonymize_pb2 as anonymize__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in anonymize_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AnonymizeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAnonymizedID = channel.unary_unary(
            "/AnonymizeService/getAnonymizedID",
            request_serializer=anonymize__pb2.SendNickname.SerializeToString,
            response_deserializer=anonymize__pb2.ReceiveID.FromString,
            _registered_method=True,
        )


class AnonymizeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAnonymizedID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnonymizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "getAnonymizedID": grpc.unary_unary_rpc_method_handler(
            servicer.getAnonymizedID,
            request_deserializer=anonymize__pb2.SendNickname.FromString,
            response_serializer=anonymize__pb2.ReceiveID.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "AnonymizeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("AnonymizeService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AnonymizeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAnonymizedID(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/AnonymizeService/getAnonymizedID",
            anonymize__pb2.SendNickname.SerializeToString,
            anonymize__pb2.ReceiveID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
