name: Publish Docker Images

# This should run only after the tests from the CI pipeline have passed.
# On a rare ocassion contributors can trigger this manually, and it should also
# run after a release has been published.
on:
  workflow_run:
    workflows: ["continuous integration (ci)"]
    types:
      - completed
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: |
            kaszanas/sc2anonserverpy
      - name: Build and Push Docker images
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
